plugins {
    id "fabric-loom" version "1.11-SNAPSHOT"
    id "org.jetbrains.kotlin.jvm"
    id "maven-publish"
}

version = "$mod_version+$minecraft_version"
group = maven_group

base {
    archivesName = mod_id
}

repositories {
    maven {
        name = "MC Brawls"
        url  = "https://maven.mcbrawls.net/releases/"
    }

    maven {
        name = "Nucleoid"
        url  = "https://maven.nucleoid.xyz/"
    }
}

sourceSets {
    test {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

loom {
    accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
    splitEnvironmentSourceSets()

    mods {
        mod_id {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    runs {
        client {
            ideConfigGenerated = false
        }

        testServer {
            inherit(server)
            name("Minecraft Server (Test)")
            source(sourceSets.test)
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings "net.fabricmc:yarn:$minecraft_version+build.$yarn_build:v2"

    modImplementation "net.fabricmc:fabric-loader:$loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_version"

    modImplementation "net.fabricmc:fabric-language-kotlin:$fabric_kotlin_version+kotlin.$kotlin_version"

    include modImplementation ("eu.pb4:polymer-core:$polymer_version")
    include modImplementation ("eu.pb4:polymer-virtual-entity:$polymer_version")

    testImplementation sourceSets.main.output
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = 21
    }
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}"}
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = mod_id
            from components.java

            pom {
                name = "Populus"
                description = "A library for creating fake players."
                url = "https://mcbrawls.net"

                licenses {
                    license {
                        name = "MIT"
                        url = "https://opensource.org/licenses/MIT"
                        distribution = "repo"
                    }
                }
            }
        }
    }

    repositories {
        def env = System.getenv()
        def mavenUrl = env["mavenUrl"]
        def mavenUsername = env["mavenUsername"]
        def mavenPassword = env["mavenPassword"]
        if (mavenUrl && mavenUsername && mavenPassword) {
            maven {
                url = mavenUrl
                credentials.username = mavenUsername
                credentials.password = mavenPassword
            }
        }
    }
}
